name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Transfer
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Transfer the executable to the server via SCP
      - name: Transfer Artifact to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './*'
          target: ~/halloween/
          overwrite: true
