name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tarball from current HEAD (no .git)
        run: |
          git archive --format=tar HEAD | gzip > repo.tar.gz

      - name: Upload tarball
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "repo.tar.gz"
          target: "~/halloween/"
          overwrite: true

      - name: Extract on server and cleanup
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/halloween
            tar -xzf ~/halloween/repo.tar.gz -C ~/halloween
            rm ~/halloween/repo.tar.gz